### ISSUE TITLE
Can't get plugin to work

### ISSUE THREAD

**Issue by palmerit** [rmohr/chroot-plugin#3] opened 2014-12-06 21:37 UTC
I'm trying to use the chroot plugin,  and have a .pbuilderrc file setup that works successfully when I run pbuilder --create manually. However, when I try to use the plugin according to the instructions on the jenkins-ci wiki,  I can't get it to actually do anything.  I just continuously get an error of:

FATAL: Failed to copy . to /var/lib/jenkins/jobs/NetHunter - OPO - KitKat/workspace/Kali
java.io.IOException: Failed to copy . to /var/lib/jenkins/jobs/NetHunter - OPO - KitKat/workspace/Kali

However I noticed, if I disable the option to "Install Automatically" it suddenly offers me an option called "Home' that seems like it needs to be a directory. However, it's unclear what that directory needs to consist of.  

I also noticed (after trying a few directories unsuccessfully) that if I have a value in there,  and then re-enable "Install Automatically" the first error message changes from "Failed to copy . to..."  to "Failed to copy foo/bar/baz to..."  and then complains that foo/bar/baz is a directory.  So,  the "Home" setting which forces you to choose a directory (and complains if it's a file) seems to be carried through to the Install automatically setting which complains that it is a directory.

If you can offer some guidance, that would be appreciated.  I intend to write up a blog post after I get it working, so others don't spend have to spend the time that I have trying to get it to work.

If it matters,  the pbuilderrc is trying to make a chroot of the kali distribution at http://http.kali.org/kali

**Comment by jonlar** [comment] 2015-01-08 11:16
I'm having this problem as well running chroot plugin 0.1.3 with jenkins 1.596. I'm running on Ubuntu 12.04.5.

Any progress/fix/workaround on the horizon?

**Comment by rmohr** [comment] 2015-01-11 19:56
Hi, I don't have much time at the moment but I will try to resolve it the next days. Could you two check if you can run pbuilder as the user which jenkins is using? Try something like "pbuilder -u <jenkins-user> pbuilder. It is important that Jenkins can run the pbuilder binary with sudo without a password.

**Comment by rmohr** [comment] 2015-01-11 20:03
Adding something like this 
```
jenkins ALL=(ALL) NOPASSWD: /usr/sbin/pbuilder
```
to /etc/sudoers should be sufficient.

**Comment by jonlar** [comment] 2015-01-12 08:18
Thanks for the input. The problem was not with the pbuilder installation, but rather that I misunderstood how to configure the chroot plugin as intended.

I've managed to build a chroot with pbuilder on my master now. Next step is to get the tool to deploy the chroot onto my slaves.

**Comment by palmerit** [comment] 2015-01-12 08:46
Jonas, I'd be interested in knowing what you misunderstood, and ultimately
what you changed to make it start working. I'm actually hoping I have the
same misunderstanding, because not having the chariot environment is a
serious roadblock for my team..

**Comment by jonlar** [comment] 2015-01-12 08:58
Make sure you select "Install automatically". Try to follow the steps outlined in the wiki documentation  https://wiki.jenkins-ci.org/display/JENKINS/chroot+Plugin

**Comment by rmohr** [comment] 2015-01-12 09:00
Glad I could help.  I would be curious too.

Btw I ment to run 
```
sudo -u <jenkins-user> pbuilder
```
in the comment above.

**Comment by rmohr** [comment] 2015-01-12 19:59
@palmerit could you try running pbuilder with sudo as jenkins user and report back? I have been debugging the problem and the root cause seems to be that the automatic installer thinks that it can not create the initial archive on the selected node.

Possible reasons:
 * Jenkins has no permission to run pbuilder
 * Jenkins user can not see /usr/sbin/pbuilder (it checks if the binary exists)

To be  honest I never tried the plugin on debian (but I have successfully created debian chroots with jenkins on ubuntu hosts)

**Comment by palmerit** [comment] 2015-01-14 21:40
Roman,

I should be able to test it this weekend.   I know I added the sudoers bit
previously, but I've tried a ton of different things to get it to work.
So, I'll rebuild the environment this weekend so I have a known working
state, and then verify that pbuilder works.



On Mon, Jan 12, 2015 at 2:59 PM, Roman Mohr <notifications@github.com>
wrote:

> @palmerit <https://github.com/palmerit> could you try running pbuilder
> with sudo as jenkins user and report back? I have been debugging the
> problem and the root cause seems to be that the automatic installer thinks
> that it can not create the initial archive on the selected node.
>
> Possible reasons:
>
>    - Jenkins has no permission to run pbuilder
>    - Jenkins user can not see /usr/sbin/pbuilder (it checks if the binary
>    exists)
>
> To be honest I never tried the plugin on debian (but I have successfully
> created debian chroots with jenkins on ubuntu hosts)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rmohr/chroot-plugin/issues/3#issuecomment-69634866>.
>



-- 
Jeff Palmer
https://PalmerIT.net

**Comment by jvgelder** [comment] 2015-01-21 13:59
I might have the same error and it seems it is trying to copy the current dir '.' to a file named after my pbuilder chroot. I use debian jessie with jenkins 1.579 and chroot-plugin version 0.1.3. Currently trying to install the plugin from source.

Error log:
```
FATAL: Failed to copy . to /var/lib/jenkins/jobs/myrepo/workspace/wheezy64
java.io.IOException: Failed to copy . to /var/lib/jenkins/jobs/myrepo/workspace/wheezy64
	at hudson.FilePath.copyTo(FilePath.java:1986)
	at org.jenkinsci.plugins.chroot.builders.ChrootBuilder$LocalCopyTo.invoke(ChrootBuilder.java:136)
	at org.jenkinsci.plugins.chroot.builders.ChrootBuilder$LocalCopyTo.invoke(ChrootBuilder.java:125)
	at hudson.FilePath.act(FilePath.java:989)
	at hudson.FilePath.act(FilePath.java:967)
	at org.jenkinsci.plugins.chroot.builders.ChrootBuilder.perform(ChrootBuilder.java:165)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at hudson.model.Run.execute(Run.java:1718)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: java.io.FileNotFoundException: . (Is a directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at hudson.FilePath$41.invoke(FilePath.java:2012)
	at hudson.FilePath$41.invoke(FilePath.java:2007)
	at hudson.FilePath.act(FilePath.java:989)
	at hudson.FilePath.act(FilePath.java:967)
	at hudson.FilePath.copyTo(FilePath.java:2007)
	at hudson.FilePath.copyTo(FilePath.java:1981)
```

**Comment by corecache** [comment] 2015-01-21 16:56
@jonlar Can you elaborate how you solved this?

**Comment by kodekarl** [comment] 2015-01-21 23:48
Same issue for me. Same stacktrace. Running Jenkins 1.580.2 LTS with chroot plug-in 0.1.3, on a Ubuntu 14.10 (two different ones with same result, actually). Freshly installed (Jenkins, not Ubuntu). I didn't change any "advanced" settings, but just performed the basic setup.

The result is the same whether the job runs on master or (localhost) slave; the stacktrace is slightly different, but the meaning is the same ("Failed to copy .")
There's no ~jenkins/pbuilder directory.
The behaviour does not depend on jenkins being able to sudo or not.
Checking the "Clear" box in the build adds these lines above the "FATAL" message:

```
Building on master in workspace /var/lib/jenkins/jobs/test/workspace
$ sudo /usr/sbin/pbuilder --clean --basetgz /var/lib/jenkins/jobs/test/workspace/test-pbuilder
W: /var/lib/jenkins/.pbuilderrc does not exist
I: Cleaning [/var/cache/pbuilder/build/]
I: removing directory /var/cache/pbuilder/build/ and its subdirectories
I: Cleaning [/var/cache/pbuilder/aptcache/]
rm: cannot remove '/var/cache/pbuilder/aptcache//*': No such file or directory
```

I do believe that I have seen some of these messages appear in a slighly different order.

I'll be happy to provide more information, just ask.

**Comment by jonlar** [comment] 2015-01-22 07:19
For me the issue was resolved by checking "Install automatically" under "Advanced settings"

I have the following settings under ":Chroot Environment installations"

Name: precise
Tool: pbuilder
Advanced Configuration: "checked"
Install packages: libc6:i386 libstdc++6:i386 gawk bison flex libwww-perl libstring-shellquote-perl libfile-slurp-perl git openssh-client time srecord ed cmake cmake-data emacsen-common texinfo autotools-de
Additional arguments: --distribution precise --debootstrapopts --variant=buildd
Shell command: <empty>
Repositories
Name: universe
Repository URL: deb http://se.archive.ubuntu.com/ubuntu/ precise universe
Keyfile URL: http://archive.ubuntu.com/ubuntu/project/ubuntu-archive-keyring.gpg
Install automatically: <checked>

Also, as previously stated, verify that your jenkins user can run pbuilder under sudo.

For each job I have a "Chroot Builder" under "Build".

Good luck!

**Comment by rmohr** [comment] 2015-01-22 08:27
Thank you for all your feedback! I have improved the pbuilder configuration checks and with the latest commits you can see why jenkins failed in the global jenkins logs.

It would be great if someone else could also try the latest HEAD. I want to do some more final checks before I release a new version (hope to do the release tonight or tomorrow).

Anyway as @jonlar sayed, most likely your jenkins user can not run pbuilder under sudo.

**Comment by corecache** [comment] 2015-01-22 09:28
@rmohr Also can you update the documentation with a short informal description of the workflow of the plugin? I've given the java stuff a look but my panic-o-matic glasses instantly blacked-out. I've built latest HEAD and give it a shot on Jenkins ver. 1.594

**Comment by corecache** [comment] 2015-01-22 09:36
Here's a dry-run with non-existant base.tgz from the jobs output:

$ sudo /usr/sbin/pbuilder --create --basetgz /var/lib/jenkins/pbuilder/foobar.tgz --extrapackages "python-software-properties sudo wget"
W: /root/.pbuilderrc does not exist
E: debootstrap failed
W: Aborting with an error
FATAL: Could not setup chroot environment
FATAL: Installation of tool foobar on node Jenkins failed.
java.io.IOException: Installation of tool foobar on node Jenkins failed.

Seems legit so far.

**Comment by rmohr** [comment] 2015-01-22 09:46
Hm, pbuilder is extremely verbose when nothing interesting is going on, but not very talkative on stderr. Maybe I should include an option to optionally also log stdout.

Could you rung the command
´´´
sudo /usr/sbin/pbuilder --create --basetgz /var/lib/jenkins/pbuilder/foobar.tgz --extrapackages "python-software-properties sudo wget"
´´´
from a terminal or in a build step of a normal freestyle job? Then you would see the whole output. But we are getting somewhere now .. :+1:

**Comment by rmohr** [comment] 2015-01-22 10:15
@corecache I have pushed another commit 24a6c9bdc6b0540c109ea which fixes #2. I have the strong suspicion that you are running into the problem mentioned there. It would be really great if you could give it another try! Tank you very much for your time!

**Comment by kodekarl** [comment] 2015-01-22 10:30
I do indeed have "Install automatically" selected - as per the instructions.
"sudo -u jenkins pbuilder" gives an error message (usage help) from pbuilder; does not exercise the sudo capabilities at all (AFAICS).
I'll make a quick testrun with a freestyle pbuilder. I've had to mkdir ~jenkins/pbuilder manually, btw - don't know if it was supposed to be created by the plug-in?

**Comment by rmohr** [comment] 2015-01-22 10:40
@kodekarl you are most likely running into #2. When you are not adding the universe repository in Ubuntu >= 14.04, pbuilder fails and the plugin gets confused. This should be fixed in 24a6c9bdc6b0540c109ea. I just want to be more convinced that my updates do not break existing installations before I do the release.

**Comment by jvgelder** [comment] 2015-01-22 11:09
@rmohr This works in a buildstep:
``` 
sudo /usr/sbin/pbuilder --create --basetgz /var/lib/jenkins/pbuilder/foobar.tgz --extrapackages "python-software-properties sudo wget"
```

But when I use the plugin it says:
But I don't know how I can see where it goes wrong.
Any ideas?
```
FATAL: The node Jenkins is not correctly setup up for pbuilder
java.io.IOException: The node Jenkins is not correctly setup up for pbuilder
	at org.jenkinsci.plugins.chroot.tools.ChrootToolset.forNode(ChrootToolset.java:93)
	at org.jenkinsci.plugins.chroot.builders.ChrootBuilder.perform(ChrootBuilder.java:145)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at hudson.model.Run.execute(Run.java:1718)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

**Comment by rmohr** [comment] 2015-01-22 11:17
@jvgelder did you pull the latest changes from today? If yes, you could have a look into the jenkins log in **Manage Jenkins** -> **System Log**.

**Comment by jvgelder** [comment] 2015-01-22 11:34
For some reason it fails on:
```java
public ChrootToolset forNode(Node node, TaskListener listener) throws IOException, InterruptedException {
        String home = translateFor(node, listener);
      ---->  if (Strings.isNullOrEmpty(home)) {
            throw new IOException("The node " + node.getDisplayName() + " is not correctly setup up for " + this.getToolName());
        }
        return new ChrootToolset(getName(), translateFor(node, listener), getToolName(), getProperties().toList());
    }
```

But I do not know enough about the jenkins api.

In the log all I see is:

```
n 22, 2015 12:16:51 PM hudson.WebAppMain$2 run
INFO: Jenkins is fully up and running

Jan 22, 2015 12:16:51 PM hudson.TcpSlaveAgentListener <init>
INFO: JNLP slave agent listener started on TCP port 54241

Jan 22, 2015 12:16:51 PM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization

Jan 22, 2015 12:16:51 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs

Jan 22, 2015 12:16:51 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions

Jan 22, 2015 12:16:51 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins

Jan 22, 2015 12:16:49 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins

Jan 22, 2015 12:16:49 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins

Jan 22, 2015 12:16:48 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
```

Which might have something to do with: 

```
Failed to load native POSIX impl; falling back on Java impl. Stacktrace follows.
java.lang.UnsatisfiedLinkError: Unable to load library 'libc.so.6': com.sun.jna.Native.open(Ljava/lang/String;)J
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:166)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:239)
        at com.sun.jna.Library$Handler.<init>(Library.java:140)
        at com.sun.jna.Native.loadLibrary(Native.java:366)
        at org.jruby.ext.posix.POSIXFactory.loadLibC(POSIXFactory.java:96)
        at org.jruby.ext.posix.POSIXFactory.loadLinuxPOSIX(POSIXFactory.java:65)
        at org.jruby.ext.posix.POSIXFactory.getPOSIX(POSIXFactory.java:24)
        at hudson.os.PosixAPI.<clinit>(PosixAPI.java:41)
        at hudson.Util.createSymlink(Util.java:1011)
        at hudson.model.Run.execute(Run.java:1500)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
        at hudson.model.ResourceController.execute(ResourceController.java:88)
        at hudson.model.Executor.run(Executor.java:237)

```

**Comment by corecache** [comment] 2015-01-22 11:58
@rmohr Im glad to say that your suspicion was wrong :) It actually starts running now, but it seems that extra options in the argument string to pbuilder + debootstrap get manipulated on the way down to the pbuiler call. I'm running a fairly complex setup here for the chroot which takes quite a bunch of arguments e.g:

--distribution myDist --mirror http://my-repo.local/myos --debootstrapopts --no-check-gpg --debootstrapopts --variant=minbase --debootstrapopts --include=my-repo-archive-keyring --allow-untrusted --othermirror 'deb http://my-repo.local/debian wheezy main contrib non-free' 

Especially the --othermirror gets truncated on the way down towards the call.

Another thing, have you thought about using "schroot" for the setup? This would improve the speed of setting up the chroot to just a few seconds.

**Comment by kodekarl** [comment] 2015-01-22 12:54
Sorry, will have to postpone testing until I get home; work is too busy today and this is less important.
I would not mind testing the new changes, but I cannot build a plug-in myself. Is there a place I can pick-up a built hpi?

**Comment by kodekarl** [comment] 2015-01-22 13:06
Just another quick note: I'm not sure that the "Failed to copy ." has much to do with whether pbuilder is sudo or not, or setup correctly or not. To me, it looks more like it's failing _before_ pbuilder is started?
And yes, I haven't setup the "universe" repository - the Jenkins server here does not have access to the Internet, and I couldn't easily find a link to the keyring on our internal mirror. Will try at home.
I've run pbuilder outside of Jenkins, and it managed to create a tgz with just this command (run as jenkins) : "sudo pbuilder --create --basetgz /var/lib/jenkins/pbuilder/test-pbuilder.tgz". I don't know if this runs without universe or a default universe...

**Comment by kodekarl** [comment] 2015-01-22 20:40
Following up from home now :-)
I put this command in a new freestyle job:
```
sudo /usr/sbin/pbuilder --create --basetgz foobar.tgz --extrapackages "python-software-properties sudo wget"
```
(note the non-absolute path on basetgz -- /var/lib/jenkins/pbuilder does not exist)
The command runs nicely until near the end, where it fails with:
```
Package python-software-properties is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  software-properties-common
```
Just like you said it would. I retried with the new package name instead, which results in the succesful build of a 122 MB tgz.

I also made sure to add the "universe" repository on my chroot setup (still running 0.1.3), and it made absolutely no difference on the job that uses the chroot plug-in:
```
$ sudo /usr/sbin/pbuilder --clean --basetgz /var/lib/jenkins/jobs/test/workspace/test-pbuilder
W: /var/lib/jenkins/.pbuilderrc does not exist
I: Cleaning [/var/cache/pbuilder/build/]
W: directory /var/cache/pbuilder/build/ does not exist in clean_subdirectories
I: Cleaning [/var/cache/pbuilder/aptcache/]
rm: cannot remove '/var/cache/pbuilder/aptcache//*': No such file or directory
FATAL: Failed to copy . to /var/lib/jenkins/jobs/test/workspace/test-pbuilder
```
This job has "Clear" set in its builder.

I was browsing a bit through the source code (Java is not my native language), and with the error message I/we get (indicating that the path to "tarball" is "."), and the failure of isNullOrEmpty(home) also mentioned, I'm suspecting that for some reason the expected name of the tarball and/or its "home" is not determined correctly?

Now I'll go see if today's changes can be found in a built hpi somewhere here (I'm new to github, you know...). ... ... ... doesn't seem like it :-/

**Comment by rmohr** [comment] 2015-01-22 22:05
@kodekarl Don't worry. As soon as I get a positive feedback on issue #4 I will do the release which should fix your issue.

**Comment by kodekarl** [comment] 2015-01-22 22:07
I don't worry - I just wish I could have helped test ;-)

**Comment by corecache** [comment] 2015-01-23 07:37
@kodekarl - see the README of this repository:
* checkout
* mvn install
* Jenkins -> Manage-Plugins -> Advanced -> Upload file
* restart Jenkins

Its really that easy :)

**Comment by kodekarl** [comment] 2015-01-23 07:50
Thank you @corecache - I will try that out later. I (wrongly) assumed that I would need to setup all sorts of things beforehand (from glancing at Jenkins' plugin writing guide some time ago), so I didn't actually check.
Of course, the real complexity is hidden in that innocent looking "mvn install" line ;-)

**Comment by corecache** [comment] 2015-01-23 08:45
@mrohr interestingly enough I ran into your  exception in ChrootToolset.java:93 within the build of abc93342a00b66c0d30184f09832d7462ec8070f - after I fiddled around a bit (credentials, rotating old builds), although it had build before successfully. So somehow it was back to state saying that the node is not setup for it, whereas it was and had done so successfully.

**Comment by rmohr** [comment] 2015-01-23 09:11
@corecache do the jenkins system logs show something?

**Comment by corecache** [comment] 2015-01-23 09:22
@rmohr Nothing in particular, if it happens again Ill drop a new issue.

**Comment by kodekarl** [comment] 2015-01-23 22:14
I built the plug-in from abc9334, and got the same message that @corecache mentions: "FATAL: The node Jenkins is not correctly setup up for pbuilder". And absolutely nothing in the Jenkins log. Does it log in some other "context/name" than the global log?
I then did what @corecache suggested: Remove the chroot environment and the build step. I get the same message again: "FATAL: The node Jenkins is not correctly setup up for pbuilder" (from ChrootToolset.java:93).
I only have the master, and no slaves. And then it dawned on me: I had entered a label ("test") in the Chroot Environment setup (for the automatic installer), but I don't have that label on master.
So I deleted the label in the setup ... and almost magically, the build has started creating a tarball :-)
I'll report back when it finishes...

**Comment by kodekarl** [comment] 2015-01-23 22:44
First build failed, but that was my fault: I had left a file in the workspace called test-pbuilder, and apparently the plug-in wanted to use that as a directory name (it's the name of the chroot env).
Next build worked :)
May I suggest to reword the error message a little (apart from the "setup up" part)? Something like:
"The pbuilder tool is not able to run on node Jenkins - perhaps node is missing a label?" (or instead of "not able", use "not configured").
Even better would be if it was possible to ascertain that it _was_ missing the label ;)  I don't know what else could be wrong, but probably plenty...
Just a suggestion. Use or not. Thanks for fixing.

**Comment by jvgelder** [comment] 2015-01-24 14:29
@kodekarl Thanks a lot for pointing that out about the label thing. I left it empty and now it works! @rmohr I don't quiet understand what the installer label does maybe you could elaborate this a bit more ?

**Comment by kodekarl** [comment] 2015-01-24 23:03
As far as I understand the label, we can use it to tell Jenkins where (master/slaves) a chroot environment will (or should) be available, which is on the node (or nodes) that have the given label.
We just need to ensure that that node actually _does_ have that label, or we'll get that slightly cryptic message about "not setup".
I don't _think_ that the plug-in makes any attempt to copy chroot environments around between slaves, so if we have more than a single node, it's going to be important to get the labels right.

**Comment by rmohr** [comment] 2015-02-01 20:48
The new version 0.1.4 is released. It should be available in your plugin installation center within a day or so.

@jvgelder @kodekarl  as you two already pointed out correctly: The label is just an optional possiblity to restrict the chroot creation to specific nodes. That is a standard [Jenkins feature](https://wiki.jenkins-ci.org/display/JENKINS/Tool+Auto-Installation).

@palmerit This should solve your problem as well.

Thank you all very much for your help!

**Closed by rmohr** 2015-02-01 20:48 UTC
Labels: bug

**Comment by corecache** [comment] 2015-02-02 11:47
@rmohr Thanks a bunch

**Comment by abrahammartin** [comment] 2015-02-27 14:30
I'm getting the following error using 0.1.4

    FATAL: The node Jenkins is not correctly setup up for pbuilder
    java.io.IOException: The node Jenkins is not correctly setup up for pbuilder
    	at org.jenkinsci.plugins.chroot.tools.ChrootToolset.forNode(ChrootToolset.java:93)
    	at org.jenkinsci.plugins.chroot.builders.ChrootBuilder.perform(ChrootBuilder.java:145)
    	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    	at hudson.model.Build$BuildExecution.build(Build.java:199)
    	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
    	at hudson.model.Run.execute(Run.java:1718)
    	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    	at hudson.model.ResourceController.execute(ResourceController.java:89)
    	at hudson.model.Executor.run(Executor.java:240)

I can execute pbuilder with sudo without password using the jenkins_user.
I don't have nodes (only master).
I can't see any error in the jenkins log.

Any clue?

**Comment by kodekarl** [comment] 2015-03-02 23:26
@abrahammartin, did you read the comments about use of "label" above? It sounds like this could explain your described symptom.

**Comment by labs-stellios** [comment] 2015-08-10 20:02
@jvgelder, can you describe where to clear the label?  I'm not finding it on jenkins 1.624 through either the jenkins or job configuration pages.  it looks like i have the same issue as @abrahammartin on trying to build a `hello-world` app in a chroot.
